import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(override=True)

from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel

from database import get_db, sync_metadata, get_dataset_schema
from ai import generate_dax, fix_dax, format_answer, is_followup_question, answer_from_context
from powerbi import execute_query, get_reports, generate_embed_token

app = FastAPI(title="Power BI Copilot")

STATIC = Path(__file__).parent / "static"
app.mount("/static", StaticFiles(directory=STATIC), name="static")


@app.get("/")
async def root():
    return FileResponse(STATIC / "index.html")


# ---------- Workspaces ----------

@app.get("/api/workspaces")
async def list_workspaces():
    db = get_db()
    res = db.table("workspaces").select("*").order("name").execute()
    return res.data


@app.post("/api/workspaces/sync")
async def sync(force: bool = False):
    try:
        result = await sync_metadata(force=force)
        return {"success": True, **result}
    except Exception as e:
        raise HTTPException(500, str(e))


# ---------- Datasets ----------

@app.get("/api/reports/{workspace_id}")
async def list_reports(workspace_id: str):
    try:
        reports = await get_reports(workspace_id)
        return reports
    except Exception as e:
        raise HTTPException(500, str(e))


@app.get("/api/report-url/{workspace_id}/{report_id}")
async def report_url(workspace_id: str, report_id: str):
    """Return embed URL + token generated by the service principal (no user login required)."""
    try:
        token_data = await generate_embed_token(workspace_id, report_id)
        embed_token = token_data.get("token", "")
        embed_url = f"https://app.powerbi.com/reportEmbed?reportId={report_id}&groupId={workspace_id}"
        return {"url": embed_url, "token": embed_token}
    except Exception as e:
        raise HTTPException(500, f"Erro ao gerar embed token: {e}")


@app.get("/api/datasets/{workspace_id}")
async def list_datasets(workspace_id: str):
    db = get_db()
    # Use count per dataset_id to avoid the 1000-row default Supabase limit
    tables_res = db.table("tables").select("dataset_id").limit(100_000).execute()
    ds_with_schema = {r["dataset_id"] for r in (tables_res.data or [])}

    res = db.table("datasets").select("*").eq("workspace_id", workspace_id).order("name").execute()
    datasets = res.data or []
    # Add has_schema flag; only return refreshable datasets
    result = []
    for d in datasets:
        if d.get("name") in ("Report Usage Metrics Model",):
            continue
        d["has_schema"] = d["id"] in ds_with_schema
        result.append(d)
    return result


@app.get("/api/schema/{dataset_id}")
async def dataset_schema(dataset_id: str):
    return get_dataset_schema(dataset_id)


# ---------- Chat ----------

class HistoryMessage(BaseModel):
    role: str  # "user" or "assistant"
    content: str


class ChatRequest(BaseModel):
    question: str
    dataset_id: str
    history: list[HistoryMessage] = []


@app.post("/api/chat")
async def chat(req: ChatRequest):
    try:
        return await _chat_handler(req)
    except HTTPException:
        raise
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(500, f"Erro interno: {type(e).__name__}: {e}")


async def _chat_handler(req: ChatRequest):
    db = get_db()

    ds_res = db.table("datasets").select("name").eq("id", req.dataset_id).single().execute()
    if not ds_res.data:
        raise HTTPException(400, "Dataset não encontrado. Sincronize os metadados primeiro.")

    schema = get_dataset_schema(req.dataset_id)
    if not schema:
        raise HTTPException(400, "Schema vazio. Clique em 'Sincronizar Metadados' primeiro.")

    dataset_name = ds_res.data["name"]

    # If it's a follow-up clarification, answer from context without running DAX
    if is_followup_question(req.question, req.history):
        if not req.history:
            return {"question": req.question, "dax_query": None, "rows": [], "row_count": 0,
                    "answer": "Não tenho contexto da pergunta anterior. Por favor, faça uma pergunta específica sobre os dados."}
        answer = await answer_from_context(req.question, req.history)
        return {"question": req.question, "dax_query": None, "rows": [], "row_count": 0, "answer": answer}

    dax = await generate_dax(req.question, schema, dataset_name, req.history)

    rows = []
    query_error = None
    try:
        rows = await execute_query(req.dataset_id, dax)
    except Exception as e:
        query_error = str(e)

    # Auto-retry: ask AI to fix DAX on error
    if query_error:
        try:
            dax = await fix_dax(dax, query_error, req.question, schema, dataset_name)
            rows = await execute_query(req.dataset_id, dax)
            query_error = None
        except Exception as e2:
            query_error = str(e2)

    if query_error:
        answer = (
            f"Não foi possível executar a query mesmo após correção automática.\n\n"
            f"Erro: {query_error}"
        )
    else:
        answer = await format_answer(req.question, dax, rows, schema, req.history)

    return {
        "question": req.question,
        "dax_query": dax,
        "rows": rows,
        "row_count": len(rows),
        "answer": answer,
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=int(os.getenv("PORT", 8000)), reload=True)
